package com.magus.isis.net.res.domain;


import com.magus.isis.net.res.base.BaseDomain;

public class FavoritesDomain extends BaseDomain {
    /**
     * column:t_favorites.ID
     * comment:唯一ID
     */
    private Integer id;

    /**
     * column:t_favorites.user_id
     * comment:用户关联id
     */
    private Integer userId;

    /**
     * column:t_favorites.idx
     * comment:序号
     */
    private Integer idx;

    /**
     * column:t_favorites.typex
     * comment:类型(1=图形 2=趋势 3=报表 4=视频 )
     */
    private Integer typex;

    /**
     * column:t_favorites.icon
     * comment:图标
     */
    private String icon;

    /**
     * column:t_favorites.display
     * comment:显示名称
     */
    private String display;

    /**
     * column:t_favorites.action_url
     * comment:菜单行为(1=ser url 2=[pn] 3=[url] 4=[url])
     */
    private String actionUrl;

    /**
     * column:t_favorites.hidden
     * comment:是否显示(T/F)
     */
    private String hidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.ID
     *
     * @return the value of t_favorites.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.ID
     *
     * @param id the value for t_favorites.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.user_id
     *
     * @return the value of t_favorites.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.user_id
     *
     * @param userId the value for t_favorites.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.idx
     *
     * @return the value of t_favorites.idx
     *
     * @mbggenerated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.idx
     *
     * @param idx the value for t_favorites.idx
     *
     * @mbggenerated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.typex
     *
     * @return the value of t_favorites.typex
     *
     * @mbggenerated
     */
    public Integer getTypex() {
        return typex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.typex
     *
     * @param typex the value for t_favorites.typex
     *
     * @mbggenerated
     */
    public void setTypex(Integer typex) {
        this.typex = typex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.icon
     *
     * @return the value of t_favorites.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.icon
     *
     * @param icon the value for t_favorites.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.display
     *
     * @return the value of t_favorites.display
     *
     * @mbggenerated
     */
    public String getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.display
     *
     * @param display the value for t_favorites.display
     *
     * @mbggenerated
     */
    public void setDisplay(String display) {
        this.display = display == null ? null : display.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.action_url
     *
     * @return the value of t_favorites.action_url
     *
     * @mbggenerated
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.action_url
     *
     * @param actionUrl the value for t_favorites.action_url
     *
     * @mbggenerated
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl == null ? null : actionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.hidden
     *
     * @return the value of t_favorites.hidden
     *
     * @mbggenerated
     */
    public String getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.hidden
     *
     * @param hidden the value for t_favorites.hidden
     *
     * @mbggenerated
     */
    public void setHidden(String hidden) {
        this.hidden = hidden == null ? null : hidden.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favorites
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", idx=").append(idx);
        sb.append(", typex=").append(typex);
        sb.append(", icon=").append(icon);
        sb.append(", display=").append(display);
        sb.append(", actionUrl=").append(actionUrl);
        sb.append(", hidden=").append(hidden);
        sb.append("]");
        return sb.toString();
    }
}